### ISSUE TITLE
Create a hello world backend using Express and TypeScript

### ISSUE THREAD

**Issue by aerabi** [aerabi/events#1]
Create a backend code in the `backend` directory that uses Express.js and TypeScript.

You can use [this repo](https://github.com/aerabi/nodejs-api-starter) for inspiration (it uses TSOA which in turn uses Express under the hood, you can use either: pure Express, or TSOA-wrapped Express).

⚠️ Write down each step in the README file.

**Comment by steve192** [comment]
Hi @aerabi 

I can take care of this issue. I guess the first endpoints we need are 
- Fetch all events
- Create new event


And my first suggestion for the definition of an event
- Name / Title
- Link to event
- Date when the event is happening
- Name of the organizer
