### ISSUE TITLE
Add ESLint to frotend project

### ISSUE THREAD

**Issue by aerabi** [aerabi/events#10]
We should add ESLint to the frontend project and enforce the recommended rules. E.g. the `.eslintrc.js` file should contain the following content.

```js
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 2020,
    sourceType: 'module',
  },
  extends: ['plugin:@typescript-eslint/recommended', 'prettier', 'plugin:prettier/recommended'],
  rules: {},
};
```

You can use [this repo](https://github.com/rxjsx/rxjsx) as a reference for the `prettier` rules, `eslint` rules, and the packages to be installed.

We should add the following NPM commands to the backend project:
- `npm run lint`: Fix the fixable lint issues (including prettier)
- `npm run lint:test`: Just check if the code is well-formatted (used in the CI)

**Comment by himanshukandpal-28** [comment]
Hey @aerabi can I pick up this task?

**Comment by aerabi** [comment]
It's all yours, Himanshu (@himanshukandpal-28). Happy coding. 🎉

**Comment by himanshukandpal-28** [comment]
Hey folks raised the PR https://github.com/aerabi/events/pull/18 for issue

**Comment by himanshukandpal-28** [comment]
Hey @aerabi  I have raise the [PR](https://github.com/aerabi/events/pull/18) you check , also shall I pick changes for backend as they would be similar?

**Comment by aerabi** [comment]
Nice work, @himanshukandpal-28! Please comment on the other issue as well, so that I can assign you to it. 🙏
