### ISSUE TITLE
Create GitHub Action to check test for backend

### ISSUE THREAD

**Issue by aerabi** [aerabi/events#12]
Create a GitHub action job (in the same workflow as the one created in #2) that checks if the tests run successfully.

This action requires a MongoDB "service".

**Comment by himanshukandpal-28** [comment]
Hey @aerabi I can pick up this one also, worked on something similar earlier

**Comment by himanshukandpal-28** [comment]
Hey @aerabi  added the test check step https://github.com/aerabi/events/pull/20
