### ISSUE TITLE
Create GitHub Action to check build for backend

### ISSUE THREAD

**Issue by aerabi** [aerabi/events#2]
Create GitHub action that checks whether the backend builds successfully.

⚠️ Write down each step in the README file.

**Comment by sreekeshiyer** [comment]
Can take this up. Please assign this issue to me.

**Comment by aerabi** [comment]
It's all yours @sreekeshiyer. Happy coding. 🎉

**Comment by aerabi** [comment]
I guess it also depends on #1.

**Comment by sreekeshiyer** [comment]
Ah, guess I'll have to wait for the projects to be setup
The test directories are going to be `backend/tests` and `frontend/tests` I have to assume.
Could probably write workflows for the same.

For the compilation of typescript, do you think an `npm run lint` is sufficient?

**Comment by aerabi** [comment]
The tests are distributed in the code-base and have the pattern `*.spec.ts`. But for both projects (frontend and backend) a simple `npm test` should run the tests (the backend project requires a MongoDB instance running as well).

I also have added issues to add ESLint to the projects.

To check the syntax, you can run `npm run build`. Let's shrink the scope of this issue to testing build only, and I'll create more issues for other stuff. 🙏 

CC @sreekeshiyer

**Comment by sreekeshiyer** [comment]
> I also have added issues to add ESLint to the projects.

Great!

> To check the syntax, you can run `npm run build`. Let's shrink the scope of this issue to testing build only, and I'll create more issues for other stuff. 🙏

Fair enough. Will get that done.

**Comment by sreekeshiyer** [comment]
Take a look @aerabi 😄

**Comment by aerabi** [comment]
Nice job, @sreekeshiyer! Do you want to do #11 as well?

**Comment by sreekeshiyer** [comment]
> Nice job, @sreekeshiyer! Do you want to do #11 as well?

Sure
Please assign that as well. Not a lot to change on that one.

**Comment by aerabi** [comment]
Apparently, I can assign it to only if you leave a comment there. 🤔
