### ISSUE TITLE
Add Dockerfiles for front/backend and create a docker-compose config to run the application

### ISSUE THREAD

**Issue by steve192** [aerabi/events#6]
Depends on #5 and #4 to be merged.

Currently there is no simple way to run the entire application and Dockerfiles are needed for front and backend. Also a docker-compose file that includes those two images and mongodb would be convenient.

Regarding the setup I see two options:
- Somehow include the frontend code in the backend Dockerimage and use the express server to serve the frontend
- Setup a small nginx reverse proxy to route frontend requests to a frontend server and backend requests to the backend server
Any preferences/ideas about this?

Btw you can assign me to this issue, will take care of it

**Comment by aerabi** [comment]
I would go with NGINX and Docker compose, so the second option. Later we can create a Kubernetes deployment out of the Docker compose file. 💪

**Comment by steve192** [comment]
Perfect, implemented it this way 👌

**Comment by aerabi** [comment]
Your implementation speed is higher than my reviewing speed. 😅 Aren't you a relative of Barry Allen?
